name: Test, Build, and Deploy
runs-on: ubuntu-latest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  setup:
    name: Setup ğŸ—ï¸
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

  integrate:
    name: Integrate ğŸ”Œ
    needs: setup
    steps:
      - name: Install ğŸ’¿
        run: npm install
      - name: Unit Tests ğŸ‰
        run: npm run test

  deploy:
    name: Deploy ğŸš€
    needs: [setup, integrate]
    steps:
      - name: Build ğŸ› ï¸
        run: npm run build 
      - name: GitHub Pages ğŸ“„
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build