name: Test, Build, and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    name: Checkout ğŸ›ï¸
      uses: actions/checkout@v2

    integrate:
      - name: Integrate

      - name: Install ğŸ’¿
        run: npm install
      
      - name: Unit Tests ğŸ‰
        run: npm run test

    deploy:
      needs: integrate
      - name: Deploy

      - name: Build ğŸ› ï¸
        run: npm run build
      
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build